//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AT_SchedaTecnica
    {
        public int ID { get; set; }
        public int IDTipoScheda { get; set; }
        public int IDStatoMezzo { get; set; }
        public Nullable<int> CE110 { get; set; }
        public Nullable<int> CE112 { get; set; }
        public Nullable<int> CE115 { get; set; }
        public Nullable<int> CE125 { get; set; }
        public Nullable<int> CE135 { get; set; }
        public Nullable<int> CE145 { get; set; }
        public Nullable<int> CE150 { get; set; }
        public Nullable<int> CE160 { get; set; }
        public Nullable<int> CE170 { get; set; }
        public Nullable<int> CE415 { get; set; }
        public Nullable<int> CE265 { get; set; }
        public Nullable<int> CE420 { get; set; }
        public Nullable<int> CE816 { get; set; }
        public Nullable<int> CE840 { get; set; }
        public Nullable<int> CE841 { get; set; }
        public Nullable<int> CE842 { get; set; }
        public Nullable<int> CE843 { get; set; }
        public Nullable<int> CE844 { get; set; }
        public Nullable<int> CE960 { get; set; }
        public Nullable<int> CI820 { get; set; }
        public Nullable<int> CI825 { get; set; }
        public Nullable<int> CI835 { get; set; }
        public Nullable<int> CI837 { get; set; }
        public Nullable<int> CI843 { get; set; }
        public Nullable<int> CI910 { get; set; }
        public Nullable<int> CI930 { get; set; }
        public Nullable<int> CI1145 { get; set; }
        public Nullable<int> CS240 { get; set; }
        public Nullable<int> CS510 { get; set; }
        public Nullable<int> CS511 { get; set; }
        public Nullable<int> CS710 { get; set; }
        public Nullable<int> CS715 { get; set; }
        public Nullable<int> CS810 { get; set; }
        public Nullable<int> CS815 { get; set; }
        public Nullable<int> PS165 { get; set; }
        public Nullable<int> PS225 { get; set; }
        public Nullable<int> PS230 { get; set; }
        public Nullable<int> PS235 { get; set; }
        public Nullable<int> PS250 { get; set; }
        public Nullable<int> PS260 { get; set; }
        public Nullable<int> PS410 { get; set; }
        public Nullable<int> PS512 { get; set; }
        public Nullable<int> PS610 { get; set; }
        public int IDPratica { get; set; }
    
        public virtual AT_StatiMezzo AT_StatiMezzo { get; set; }
        public virtual AT_TipiScheda AT_TipiScheda { get; set; }
        public virtual AT_IndiciValutazione AT_IndiciValutazione { get; set; }
        public virtual AT_IndiciValutazione AT_IndiciValutazione1 { get; set; }
        public virtual AT_IndiciValutazione AT_IndiciValutazione2 { get; set; }
    }
}
